hash-format = "sha256"

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "1de39da04f5e8ab4595f4c2cd36710bc29a661311c5616e6af6af270d2506aed"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/harpy-express-mod.pw.toml"
hash = "eef7202317af41b2b93026c762be2a89bf7bae1ac98217152f0e13d351c3cb70"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "c101256f1378c97c9fc082cd2cebb2f90e358fc6602d11e15e65cc5d535d3528"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/ratatouille.pw.toml"
hash = "eb971dad4161757c8f054c34459fd13276f6fe1eeb838cdc1b883cc6b9652611"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "272b27d64cd27b909567437683287909b35de9f78db27214efb1d5e4334f9f82"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "4ea85fa7d750bf5a167fe9652f2ac896d12ab068dacb8b04539e316ba5b74042"
metafile = true

[[files]]
file = "mods/text-to-voice.pw.toml"
hash = "dbb84e3fec719a729c9bfdf1230e3bce681f341ab52f07a0c7ede8cd0115a054"
metafile = true

[[files]]
file = "mods/tmm-conductor.pw.toml"
hash = "9afc62e3b2e5d91f1cb019fce2a885f2975e90e34d4aaf57528a6b57f00cdb33"
metafile = true

[[files]]
file = "mods/tmm-haunting.pw.toml"
hash = "f84e4ec884a689cfecef5d771f4a619888e8572e19fd1ffb0911086322b04c00"
metafile = true

[[files]]
file = "mods/tmm-tts.pw.toml"
hash = "31077ba2a281c64bf433838be6534b8e2b2476a2778dbd5e8f07a6003b6b2a48"
metafile = true

[[files]]
file = "servers.dat"
hash = "17a9b86204e69c6a054eba1083b0bce523556e2b893f74bc476208d4e2ad7801"
