hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "deae5507dd9c040cf1cffb43fb7027c672f0cff5bd19a64d7f881f6bcce34af0"

[[files]]
file = "config/invmove.json"
hash = "4d6cf3ae25ee77111637bdbcb8dda77e96389e2e0924851cfd50cc04ee1cc9e0"

[[files]]
file = "config/sound_physics_remastered/occlusion.properties"
hash = "ebbac45fbb3ca01487b85ffee9601b213b71896e6606fb297bcb0f3ac9c30ffb"

[[files]]
file = "config/sound_physics_remastered/reflectivity.properties"
hash = "e26b00784bb6239988759ed1a64551b9f301dc33c5a855d91e976ee4bf40ac8a"

[[files]]
file = "config/sound_physics_remastered/sound_rates.properties"
hash = "49ec4ae36c8be0891866d6a14c18af5471e503b0f3e5940f05fa17171b2487f8"

[[files]]
file = "config/sound_physics_remastered/soundphysics.properties"
hash = "068ccd6b0985f7ba643fb7ccd6e8149378b4679891a90aa2c787f8ba278330c6"

[[files]]
file = "config/voicechat/category-volumes.properties"
hash = "94c1c4f70e5b995fbd71e86d4fa646030437fecae0685875b560a55fbd0d0e56"

[[files]]
file = "config/voicechat/player-volumes.properties"
hash = "0332261861a5ace96f503e85b0d48a8df74ea6c2f3545cd229543a6afb55ad96"

[[files]]
file = "config/voicechat/translations.properties"
hash = "693643b1d393cbb3ea7f062afc4474fcd66e4036c4f8d7c056434979cbf512d1"

[[files]]
file = "config/voicechat/username-cache.json"
hash = "44136fa355b3678a1146ad16f7e8649e94fb4fc21fe77e8310c060f61caaff8a"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "94bb978f85f2db437c6fc9e260f3c445f42535d66eca78925a0d17e0df93c9e3"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "f6d1296d15bd9df6f1cd0903c17dcf066fdc2daadf1e550d5a1fbf8789a482de"

[[files]]
file = "mods/architects-palette.pw.toml"
hash = "9d72860b804991371eec905c5e5bc78d860656b23c6891119eaf9498c6bcda41"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/armisteel.pw.toml"
hash = "98302914d658beb1d9df2a6d71441251aed4f539f1f62edd079644825a38f27e"
metafile = true

[[files]]
file = "mods/artsandcrafts.pw.toml"
hash = "5dde461c1f6c0127ed8f4e4492adec5656af768185f6fde123d04fd303e7dff4"
metafile = true

[[files]]
file = "mods/axiom.pw.toml"
hash = "b16906634dc8b2a07d43cdc6ba766e642e18458f7e7b9aaef8a374e5e7fd04dc"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
hash = "e5196147e561521c5a3ebaea601191e442d252cc8f0a7be8ba8db136f93c44fe"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/ears.pw.toml"
hash = "1de39da04f5e8ab4595f4c2cd36710bc29a661311c5616e6af6af270d2506aed"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "2e705f04feb06d4340c59aebe8430c79a48635f6cd40b5c9f9ea7e4e6500721a"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "2600fb5f2efa6dffd1bcc04eea4c2646c101da4320da0c88d5616d5c2f41a439"
metafile = true

[[files]]
file = "mods/harpy-express-mod.pw.toml"
hash = "eef7202317af41b2b93026c762be2a89bf7bae1ac98217152f0e13d351c3cb70"
metafile = true

[[files]]
file = "mods/headpat.pw.toml"
hash = "476cee1d0c5080061c4cc609f692028b118f7084e22dfed8b8f709550465cffc"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "fff3bd7b56f7f5866bacf83173ceb9d24c0a2684e4de6f8cb4d7f0173ff78455"
metafile = true

[[files]]
file = "mods/jinxedlib.pw.toml"
hash = "2aa483960df75b01d3a1e08fcce318e53da714d26b0109463721f8eb6c7e062b"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/mcqoy.pw.toml"
hash = "cc43f113dffb7f6b4a93b8f7603d59c0ab113fd6a211224bb87938ba68be72a4"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d917697e84a95f857a447d26f94d93169a5a62176c93193cdf80c8d8bc1e280a"
metafile = true

[[files]]
file = "mods/nightlights.pw.toml"
hash = "6b63d15284f95807dd5dcf19e6c1d0132cbac508426162d8db775a1c3a6a228d"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "2e2c1b47b513663871e71c89a699c66ac9fcc97633f007ed064ce4410f220f5a"
metafile = true

[[files]]
file = "mods/ratatouille.pw.toml"
hash = "eb971dad4161757c8f054c34459fd13276f6fe1eeb838cdc1b883cc6b9652611"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d3f633dd12cd039a4e58dd398d1c80a324b0d78b9da5b3972b69640bfed211ed"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "272b27d64cd27b909567437683287909b35de9f78db27214efb1d5e4334f9f82"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "4ea85fa7d750bf5a167fe9652f2ac896d12ab068dacb8b04539e316ba5b74042"
metafile = true

[[files]]
file = "mods/text-to-voice.pw.toml"
hash = "f99ede2cffd3f992e070fbeb6597f82eb748d37a4ca86d2eaed398f7dce91b88"
metafile = true

[[files]]
file = "mods/tmm-construct.pw.toml"
hash = "4613ed00c349204159ba1569a74d9f4986dd4196f5779efa7ed32ade26590366"
metafile = true

[[files]]
file = "mods/tmm-tts.pw.toml"
hash = "42f8b22f30569bab1da70422ed28da7b68cd82f5ff3800da63359f26ec4e7500"
metafile = true

[[files]]
file = "mods/umbraexpress.pw.toml"
hash = "74adc67590a1731ed554a6aefd3f87727d64299842355e56d296a427b5e83498"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8ffa4ba1466882a5abef6c6d220824f1ce4e228771f854f19e4fceb80598723c"
metafile = true

[[files]]
file = "servers.dat"
hash = "17a9b86204e69c6a054eba1083b0bce523556e2b893f74bc476208d4e2ad7801"
