name = "The Last Voyage of the Harpy Express (Bombastic Edition)"
author = "Spirit Studios"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38d1107652d9d6aab216e47a733482fc93fa835be6eb3f0946e2233e378be196"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
