name = "The Last Voyage of the Harpy Express (Bombastic Edition)"
author = "Spirit Studios"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8406992c400ad5f2478c921c88ff88505a274e300f6a8f86488806b737620aa3"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
