name = "The Last Voyage of the Harpy Express (Bombastic Edition)"
author = "Spirit Studios"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "deccf1bd600257398dc318b605750ebcc4d9333c3c66f2f51c9fd830385fccc4"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
