name = "The Last Voyage of the Harpy Express (Bombastic Edition)"
author = "Spirit Studios"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aafda3e88bfcef4c2f66c1a428f519a9b8210b96d5244ad2638163138da92f79"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
