name = "The Last Voyage of the Harpy Express (Bombastic Edition)"
author = "Spirit Studios"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0a918415d02c28cc5eb1d50b3b63d8868a17b4fa9d969f4e0419b2779a61aa7"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
