name = "The Last Voyage of the Harpy Express (Bombastic Edition)"
author = "Spirit Studios"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0aa5e88e0551f5143ee3f91224253daed90f1a0158ad559d16a747c9669cb1f"

[versions]
fabric = "0.18.1"
minecraft = "1.21.1"
